require 'concerns/uniquely_named_spec'
require 'concerns/meta_info_spec'
require 'concerns/translatable_spec'
require 'concerns/validatable_spec'
require 'concerns/renderable_spec'
require 'concerns/publishable_spec'
require 'concerns/blueprintable_spec'
require 'concerns/serializable_spec'
